---

version: '3.9'

services:
  db:
    image: postgres:15.2
    restart: unless-stopped
    env_file: ./.env
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - db_init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  guacd:
    image: guacamole/guacd:1.5.1
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - guacd_drive:/drive
      - guacd_record:/var/lib/guacamole/recordings

  guacamole:
    image: atompi/guacamole:1.5.1
    restart: unless-stopped
    env_file: ./.env
    networks:
      - default
      - proxy
    volumes:
      - guacd_record:/var/lib/guacamole/recordings
    depends_on:
      - guacd
      - db

volumes:
  guacd_drive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/guacd/drive
  guacd_record:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/guacd/record
  db_init:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/db/init
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/db/data

networks:
  proxy:
    external: true
    name: nginx_proxy
